### ISSUE TITLE
Bug: Pinning not possible anymore

### ISSUE THREAD

**Issue by se38** [fidley/VerticalTabs-Update-Site#10]
In version 0.0.0.202307201914 pinning doesn't work anymore. 

Steps to reproduce:
- mark tab as pinned
- close tab with "X" on real tab (not vertical tab) or <ctrl>+w

Result -> tab disappeared from "vertical tabs"

**Comment by fidley** [comment]
Damn.... Will repair this today. Thanks for pointing out.

**Comment by se38** [comment]
... or you may simply role back to the previous version an go to vacations

**Comment by fidley** [comment]
Nee, I wouldn't be able to have fun If I would new I haven't corrected it. 
#11
